#! /bin/bash

if [[ $1 == "--help" ]]
then
  cat /usr/share/Volatizer/HelpFiles/bootmode.md
  exit
fi

# Root check
if [[ $(whoami) != "root" ]]
then
  echo 'This script needs to run as root! Please use "sudo" in front.'
  exit
fi

if [[ -z $1 ]]
then
  SaveUser=$SUDO_USER
else
  SaveUser=$1
fi

Wait=true
while [[ $Wait == true ]] # If saving is in progress it will wait till it's done.
do
  if [[ -e /tmp/volatizer-saving ]]
  then
    echo 'Another saving process is in progress! Waiting...'
    sleep 1 # Do not exit hire, let it save once again, it is possible that files have been modified during the current saving process...
  else
    Wait=false
  fi
done

if [[ $(volatizer-mode) == "Volatile" ]]
then
  touch /tmp/volatizer-saving #The existence of this file means that a saving process is in progress, to avoid 2 saving process at the same time interfering.
  mkdir /volatizertmp
  mount $(grep "errors=remount-ro" /etc/fstab | awk '{ print $1 }') /volatizertmp
  if [[ -z $(df | grep /volatizertmp) ]]
  then
    echo 'Error! Failed to mount system partition! It may be broken or removed... Failed to set bootmode!'
    exit
  else
    if [[ $1 == "-n" && ! -f /volatizertmp/normalboot ]]
    then
      echo ''
      echo 'Setting bootmode to Normal'
      touch /volatizertmp/normalboot
    fi
    if [[ $1 == "-v" && -f /volatizertmp/normalboot ]]
    then
      echo ''
      echo 'Setting bootmode to Volatile'
      rm /volatizertmp/normalboot
    fi
    umount $(grep "errors=remount-ro" /etc/fstab | awk '{ print $1 }')
    if [[ ! -z $(df | grep /volatizertmp) ]]
    then
      echo "Error! Failed to unmount the system partition!"
      exit
    else
      rmdir /volatizertmp
      rm /tmp/volatizer-saving
    fi
  fi
  echo 'Done!'
else
  if [[ $1 == "-n" && ! -f /normalboot ]]
  then
    echo ''
    echo 'Setting bootmode to Normal'
    touch /normalboot
  fi
  if [[ $1 == "-v" && -f /normalboot ]]
  then
    echo ''
    echo 'Setting bootmode to Volatile'
    rm /normalboot
  fi
  echo 'Done!'
fi

read -t 5 -p "Do you want to reboot now? (y/n): " Yy
if [[ $Yy == [Yy]* ]]
then
  volatizer-save -R
fi
